-- ─────────────────────────────────────────────────────────────────────────────
-- Today / Tomorrow restructure: 5 matches per day, 3 tips per match.
-- Replaces the old 5-slot model (ace_prediction_slots).
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Remove the old cron jobs.
select cron.unschedule(jobid)
from cron.job
where jobname in ('ace-daily-predictions', 'ace-clear-daily-predictions');

-- 2. Drop old functions that reference the old tables.
drop function if exists public.manage_ace_prediction_slot(
  text, smallint, boolean, text, text, text, text, text, text, smallint, text, text, text
);
drop function if exists public.ace_archive_game_history();
drop function if exists public.ace_set_game_result(text, date, smallint, text);
drop function if exists public.ace_get_game_history(integer);

-- 3. Drop old tables.
drop table if exists public.ace_game_history;
drop table if exists public.ace_prediction_slots;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Live matches, keyed by (match_date, slot).
-- ─────────────────────────────────────────────────────────────────────────────
create table public.ace_matches (
  id               bigint generated by default as identity primary key,
  match_date       date        not null,
  slot             smallint    not null check (slot between 1 and 5),
  published        boolean     not null default false,
  team_a           text        not null default '',
  team_b           text        not null default '',
  league           text        not null default '',
  kickoff          text        not null default '',
  tip_over25       text        not null default '',
  tip_halffull     text        not null default '',
  tip_highest_half text        not null default '',
  slip_image       text,
  ad_zone_id       text        not null default '',
  ad_url           text        not null default '',
  source           text        not null default 'manual',
  source_fixture_id bigint,
  generated_at     timestamptz,
  updated_at       timestamptz not null default now(),
  unique (match_date, slot)
);

alter table public.ace_matches enable row level security;

create policy "Anyone can read ACE matches"
  on public.ace_matches for select to anon, authenticated using (true);

grant select on public.ace_matches to anon, authenticated;
revoke insert, update, delete on public.ace_matches from anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Archived matches for the weekly tracker (one result per match).
-- ─────────────────────────────────────────────────────────────────────────────
create table public.ace_game_history (
  id               bigint generated by default as identity primary key,
  match_date       date        not null,
  slot             smallint    not null check (slot between 1 and 5),
  team_a           text        not null,
  team_b           text        not null,
  league           text        not null,
  kickoff          text        not null,
  tip_over25       text        not null default '',
  tip_halffull     text        not null default '',
  tip_highest_half text        not null default '',
  result           text        not null default 'pending'
                     check (result in ('pending', 'win', 'loss')),
  created_at       timestamptz not null default now(),
  unique (match_date, slot)
);

alter table public.ace_game_history enable row level security;

create policy "Anyone can read ACE game history"
  on public.ace_game_history for select to anon, authenticated using (true);

grant select on public.ace_game_history to anon, authenticated;
revoke insert, update, delete on public.ace_game_history from anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Public read: returns today + tomorrow matches using the business-day rule
--    (the active "today" advances at 23:00 Lagos time, not midnight).
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.get_ace_matches_by_day()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  lagos_now        timestamp;
  lagos_date       date;
  business_today   date;
  business_tomorrow date;
begin
  lagos_now  := now() at time zone 'Africa/Lagos';
  lagos_date := lagos_now::date;
  business_today := case
    when extract(hour from lagos_now) < 23 then lagos_date
    else lagos_date + 1
  end;
  business_tomorrow := business_today + 1;

  return jsonb_build_object(
    'businessToday', to_jsonb(business_today),
    'businessTomorrow', to_jsonb(business_tomorrow),
    'today', coalesce(
      (select json_agg(sub) from (
         select * from public.ace_matches
         where match_date = business_today
         order by slot
       ) sub),
      '[]'::json
    ),
    'tomorrow', coalesce(
      (select json_agg(sub) from (
         select * from public.ace_matches
         where match_date = business_tomorrow
         order by slot
       ) sub),
      '[]'::json
    )
  );
end;
$$;

revoke all on function public.get_ace_matches_by_day() from public;
grant execute on function public.get_ace_matches_by_day() to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Admin upsert for a single match.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.manage_ace_match(
  p_admin_passcode   text,
  p_match_date       date,
  p_slot             smallint,
  p_published        boolean,
  p_team_a           text default '',
  p_team_b           text default '',
  p_league           text default '',
  p_kickoff          text default '',
  p_tip_over25       text default '',
  p_tip_halffull     text default '',
  p_tip_highest_half text default '',
  p_ad_zone_id       text default '',
  p_ad_url           text default '',
  p_slip_image       text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_result public.ace_matches;
  v_expected_hash constant text := 'd6185f398d70f2956adbe828e6a703c7b113129c575819f99d412e1176b74619';
begin
  if encode(extensions.digest(convert_to(p_admin_passcode, 'UTF8'), 'sha256'), 'hex') <> v_expected_hash then
    raise exception 'Invalid admin passcode' using errcode = '28000';
  end if;

  if p_slot not between 1 and 5 then
    raise exception 'Slot must be between 1 and 5' using errcode = '22023';
  end if;

  if p_published and (
    nullif(trim(p_team_a), '') is null or
    nullif(trim(p_team_b), '') is null or
    nullif(trim(p_tip_over25), '') is null or
    nullif(trim(p_tip_halffull), '') is null or
    nullif(trim(p_tip_highest_half), '') is null
  ) then
    raise exception 'Published matches require both teams and all three tips' using errcode = '22023';
  end if;

  insert into public.ace_matches (
    match_date, slot, published, team_a, team_b, league, kickoff,
    tip_over25, tip_halffull, tip_highest_half, ad_zone_id, ad_url, slip_image, updated_at
  ) values (
    p_match_date, p_slot, p_published,
    case when p_published then trim(p_team_a) else '' end,
    case when p_published then trim(p_team_b) else '' end,
    case when p_published then trim(p_league) else '' end,
    case when p_published then trim(p_kickoff) else '' end,
    case when p_published then trim(p_tip_over25) else '' end,
    case when p_published then trim(p_tip_halffull) else '' end,
    case when p_published then trim(p_tip_highest_half) else '' end,
    case when p_published then coalesce(trim(p_ad_zone_id), '') else '' end,
    case when p_published then coalesce(trim(p_ad_url), '') else '' end,
    case when p_published then p_slip_image else null end,
    now()
  )
  on conflict (match_date, slot) do update set
    published        = excluded.published,
    team_a           = excluded.team_a,
    team_b           = excluded.team_b,
    league           = excluded.league,
    kickoff          = excluded.kickoff,
    tip_over25       = excluded.tip_over25,
    tip_halffull     = excluded.tip_halffull,
    tip_highest_half = excluded.tip_highest_half,
    ad_zone_id       = excluded.ad_zone_id,
    ad_url           = excluded.ad_url,
    slip_image       = excluded.slip_image,
    updated_at       = now()
  returning * into v_result;

  return to_jsonb(v_result);
end;
$$;

revoke all on function public.manage_ace_match(
  text, date, smallint, boolean, text, text, text, text, text, text, text, text, text, text
) from public;
grant execute on function public.manage_ace_match(
  text, date, smallint, boolean, text, text, text, text, text, text, text, text, text, text
) to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. Admin: mark an archived match win / loss / pending.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.ace_set_match_result(
  p_admin_passcode text,
  p_match_date     date,
  p_slot           smallint,
  p_result         text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.ace_game_history;
  v_expected_hash constant text := 'd6185f398d70f2956adbe828e6a703c7b113129c575819f99d412e1176b74619';
begin
  if encode(extensions.digest(convert_to(p_admin_passcode, 'UTF8'), 'sha256'), 'hex') <> v_expected_hash then
    raise exception 'Invalid admin passcode' using errcode = '28000';
  end if;

  if p_result not in ('win', 'loss', 'pending') then
    raise exception 'Result must be win, loss, or pending' using errcode = '22023';
  end if;

  if p_slot not between 1 and 5 then
    raise exception 'Slot must be between 1 and 5' using errcode = '22023';
  end if;

  update public.ace_game_history
  set result = p_result
  where match_date = p_match_date and slot = p_slot
  returning * into v_row;

  if not found then
    raise exception 'No archived match for % slot %', p_match_date, p_slot using errcode = '22023';
  end if;

  return to_jsonb(v_row);
end;
$$;

revoke all on function public.ace_set_match_result(text, date, smallint, text) from public;
grant execute on function public.ace_set_match_result(text, date, smallint, text) to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. Read archived history for the tracker.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.ace_get_match_history(p_days integer default 7)
returns setof public.ace_game_history
language sql
stable
security definer
set search_path = ''
as $$
  select *
  from public.ace_game_history
  where match_date >= ((now() at time zone 'Africa/Lagos')::date - p_days)
  order by match_date desc, slot asc;
$$;

revoke all on function public.ace_get_match_history(integer) from public;
grant execute on function public.ace_get_match_history(integer) to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. Archive a day's published matches into history, then clear them.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.ace_archive_day(p_date date)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.ace_game_history (
    match_date, slot, team_a, team_b, league, kickoff,
    tip_over25, tip_halffull, tip_highest_half, result
  )
  select
    match_date, slot, team_a, team_b, league, kickoff,
    tip_over25, tip_halffull, tip_highest_half, 'pending'
  from public.ace_matches
  where match_date = p_date
    and published = true
    and nullif(trim(team_a), '') is not null
  on conflict (match_date, slot) do update set
    team_a           = excluded.team_a,
    team_b           = excluded.team_b,
    league           = excluded.league,
    kickoff          = excluded.kickoff,
    tip_over25       = excluded.tip_over25,
    tip_halffull     = excluded.tip_halffull,
    tip_highest_half = excluded.tip_highest_half;

  delete from public.ace_matches where match_date = p_date;
end;
$$;

revoke all on function public.ace_archive_day(date) from public;
grant execute on function public.ace_archive_day(date) to service_role;

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. Nightly rotation at 23:00 WAT (22:00 UTC):
--     archive today, then generate matches for today + 2 (the new tomorrow).
-- ─────────────────────────────────────────────────────────────────────────────
select cron.schedule(
  'ace-rotate-predictions',
  '0 22 * * *',
  $job$
  select public.ace_archive_day((now() at time zone 'Africa/Lagos')::date);

  select net.http_post(
    url := 'https://cvpjzaiurdpdvgostjqj.supabase.co/functions/v1/ace-daily-predictions',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', (
        select decrypted_secret
        from vault.decrypted_secrets
        where name = 'ace_automation_cron_secret'
        limit 1
      )
    ),
    body := jsonb_build_object(
      'scheduled', true,
      'date', (((now() at time zone 'Africa/Lagos')::date) + 2)::text
    )
  );
  $job$
);
