-- ──────────────────────────────────────────────────────────────────────────────
-- Game history: archive predictions after games end so admin can track
-- weekly wins / losses for 7 days.
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists public.ace_game_history (
  id          bigint generated by default as identity primary key,
  game_date   date        not null,
  slot        smallint    not null check (slot between 1 and 5),
  team_a      text        not null,
  team_b      text        not null,
  league      text        not null,
  kickoff     text        not null,
  odds        text        not null,
  tip         text        not null,
  confidence  smallint    not null default 80,
  slip_image  text,
  result      text        not null default 'pending'
                check (result in ('pending', 'win', 'loss')),
  created_at  timestamptz not null default now()
);

alter table public.ace_game_history enable row level security;

-- Anyone can read history (useful for public-facing stats later).
create policy "Anyone can read ACE game history"
  on public.ace_game_history
  for select
  to anon, authenticated
  using (true);

-- Unique constraint: one entry per game_date + slot.
create unique index if not exists uq_ace_game_history_date_slot
  on public.ace_game_history (game_date, slot);

-- Index for efficient "last 7 days" queries.
create index if not exists idx_ace_game_history_date
  on public.ace_game_history (game_date desc);

grant select on public.ace_game_history to anon, authenticated;
revoke insert, update, delete on public.ace_game_history from anon, authenticated;

-- ──────────────────────────────────────────────────────────────────────────────
-- Archive today's published predictions into history before the daily clear.
-- Called by the cron job BEFORE clearing the prediction slots.
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function public.ace_archive_game_history()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.ace_game_history (game_date, slot, team_a, team_b, league, kickoff, odds, tip, confidence, slip_image, result)
  select
    (now() at time zone 'Africa/Lagos')::date,
    s.slot,
    s.team_a,
    s.team_b,
    s.league,
    s.kickoff,
    s.odds,
    s.tip,
    s.confidence,
    s.slip_image,
    'pending'
  from public.ace_prediction_slots s
  where s.published = true
    and nullif(trim(s.team_a), '') is not null
  on conflict (game_date, slot) do update
    set team_a     = excluded.team_a,
        team_b     = excluded.team_b,
        league     = excluded.league,
        kickoff    = excluded.kickoff,
        odds       = excluded.odds,
        tip        = excluded.tip,
        confidence = excluded.confidence,
        slip_image = excluded.slip_image;
end;
$$;

revoke all on function public.ace_archive_game_history() from public;
grant execute on function public.ace_archive_game_history() to service_role;

-- ──────────────────────────────────────────────────────────────────────────────
-- Admin: record result for a specific game (win / loss).
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function public.ace_set_game_result(
  p_admin_passcode text,
  p_game_date      date,
  p_slot           smallint,
  p_result         text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.ace_game_history;
  v_expected_hash constant text := 'd6185f398d70f2956adbe828e6a703c7b113129c575819f99d412e1176b74619';
begin
  if encode(extensions.digest(convert_to(p_admin_passcode, 'UTF8'), 'sha256'), 'hex') <> v_expected_hash then
    raise exception 'Invalid admin passcode' using errcode = '28000';
  end if;

  if p_result not in ('win', 'loss', 'pending') then
    raise exception 'Result must be win, loss, or pending' using errcode = '22023';
  end if;

  if p_slot not between 1 and 5 then
    raise exception 'Slot must be between 1 and 5' using errcode = '22023';
  end if;

  update public.ace_game_history
  set result = p_result
  where game_date = p_game_date and slot = p_slot
  returning * into v_row;

  if v_row is null then
    raise exception 'No game found for date % slot %', p_game_date, p_slot using errcode = '22023';
  end if;

  return to_jsonb(v_row);
end;
$$;

revoke all on function public.ace_set_game_result(text, date, smallint, text) from public;
grant execute on function public.ace_set_game_result(text, date, smallint, text) to anon, authenticated;

-- ──────────────────────────────────────────────────────────────────────────────
-- Read game history for the past N days (default 7).
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function public.ace_get_game_history(p_days integer default 7)
returns setof public.ace_game_history
language sql
stable
security definer
set search_path = ''
as $$
  select *
  from public.ace_game_history
  where game_date >= ((now() at time zone 'Africa/Lagos')::date - p_days)
  order by game_date desc, slot asc;
$$;

revoke all on function public.ace_get_game_history(integer) from public;
grant execute on function public.ace_get_game_history(integer) to anon, authenticated;
